### PR TITLE
Issue #2 Use new multi-stage builds in Docker

### PR DESCRIPTION
**Pull request by Dreamwalker666**
Ok here is the work I have so far like discussed earlier.  I have placed the config file in the repo so it can be configured before you make your docker image.  Probably needs a rethink but I am new to docker as well :)

### CODE REVIEW

**Comment by DanielOaks** [comment]
Hmm, are we able to copy `oragono.yaml` from the build environment as well instead of bundling a new copy? feels a little weird to be bundling it is all, since it's gonna have to be upgraded with every new Oragono version. Otherwise, looks awesome, thanks for the help! :)

**Comment by Dreamwalker666** [comment]
Well my resoning is you might need to change stuff and you can't do that if we take it from the main branch.   I guess how it gets configured needs some though.

**Comment by Dreamwalker666** [comment]
hmm manybe its a none issue see here https://docs.docker.com/engine/swarm/configs/ this allows you to update configuration externally.  I know this is swarm but I am sure the other orchestration systems will have something similar.  

But that raises one question does oragono reload it's config when the file is updated?

**Comment by DanielOaks** [comment]
@Dreamwalker666 You can manually rehash Oragono externally by sending it a SIGHUP (described in more detail [here](https://github.com/oragono/oragono/blob/master/docs/INFO.md#rehashing)). 

One of my main goals when making Oragono is to make it so that the default config always serves on ports 6667+6697, and always has a sane running configuration. Because of that (and because otherwise we'll need to update the config file in this repo every time a new release happens), I think it's better to grab it from there.

I think the two main things users will want to configure will be ircd config and the motd. Are we able to make it use the defaults out of the box, but allow them to easily change them if they want to? (again, not familiar with Docker in the slightest)

**Comment by Dreamwalker666** [comment]
Yeah I'll update to use the defaults might not be able to do it till next week now though.

The config stuff I linked basically allows you to replace files on the box after deployment.  I am sure there will be a way to put your own config in through the command line though.  I suppose you can just inherit from the box anyway and put a couple of copy commands in :)

**Comment by DanielOaks** [comment]
Aha all good, being open source I'm not stressed about deadlines, have a good weekend ;)

Noice, yeah we'll work out something that goes well. By the way, feel free to join `#oragono` on Freenode if you wanna chat in realtime.

**Comment by Dreamwalker666** [comment]
Ok I have made that change.  

But one thing I had forgotten about the default config doesn't work.  The reason for this is no ipv6 addresses are bound in the box not sure if this is normal or not looking into it.

**Comment by Dreamwalker666** [comment]
Ok look slike this is standard in docker ipv4 is only configured as default (https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)

What is the 6668 port used for anyway since it's loop back only, some sort of management port?  If so couldn't that just log a warning if it can't be bound.  Of course the other's can't they need to fail.

**Comment by Dreamwalker666** [comment]
It can still listen on "127.0.0.1:6668" just not "[::1]:6668" then it will just automatically work.  I guess at the moment if someone dosn't have IPv6 enabled on their machine this will fail as well.

**Comment by DanielOaks** [comment]
...I'm not sure why this wan't merged earlier (prolly just because I wasn't too familiar with docker like a year or so ago). @csmith does this look alright to you as-is? If so I can merge it in now and we can work on #6 as we go

**Comment by DanielOaks** [comment]
Yeah for sure, makes sense. I'll merge this in as-is since it's been waiting so long then throw it back to building master. Thanks @Dreamwalker666 for submitting this work, even if it took me a dang long time to get back to it

**Pull request merged**
